name: journo
description: A cross-platform journal app for Android, Windows, Linux, and macOS.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  intl: ^0.19.0
  uuid: ^4.5.1
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  local_auth: ^2.3.0
  flutter_markdown: ^0.7.3+1
  timezone: ^0.9.4
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
